server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
#        - id: customers
#          uri: lb://Customers
#          predicates:
#            - Path=/customers/**
#          filters:
#            - CustomerFilter
#
#        #        Register
#        - id: registration-register
#          uri: lb://Registration
#          predicates:
#            - Path=/register
#        - id: registration-active
#          uri: lb://Registration
#          predicates:
#            - Path=/active
#        - id: registration-close
#          uri: lb://Registration
#          predicates:
#            - Path=/close
#
#        #        Coupons
#        - id: coupons-issue
#          uri: lb://Coupons
#          predicates:
#            - Path=/issue
#        - id: coupons-use
#          uri: lb://Coupons
#          predicates:
#            - Path=/use

        #         jsonplaceholder
        - id: jsonplaceholder-todos
          uri: https://jsonplaceholder.typicode.com/
          predicates:
            - Path=/todos
        - id: jsonplaceholder-all
          uri: https://jsonplaceholder.typicode.com/
          predicates:
            - Path=/todos/**

  application:
    name: gateway