server:
  port: 8080
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-route
          uri: ${POST_ROUTE_URI:http:localhost:8081}
          predicates:
            - Path=/users/**
          filters:
            - PrefixPaths=/api